name: Simple Sonar Scan

on:
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11 for build
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: ☕ Build Spring Boot JAR
        working-directory: back
        run: mvn clean install -DskipTests

      - name: Wait for SonarQube and create project
        run: |
          echo "Waiting for SonarQube to be ready..."
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if curl -s http://localhost:9000/api/system/status 2>/dev/null | grep -q "UP"; then
              echo "SonarQube is ready!"
              break
            fi
            echo "SonarQube not ready yet, waiting... ($elapsed seconds elapsed)"
            sleep 15
            elapsed=$((elapsed + 15))
          done
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for SonarQube"
            exit 1
          fi

      - name: Set up JDK 17 for SonarScanner
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run SonarScanner with Docker
        run: |
          docker run \
            --rm \
            --network host \
            -e SONAR_HOST_URL="http://localhost:9000" \
            -e SONAR_LOGIN="admin" \
            -e SONAR_PASSWORD="admin" \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=simple-sonar-scan \
            -Dsonar.sources=back/src,front/src \
            -Dsonar.java.binaries=back/target/classes \
            -Dsonar.java.source=11